[workspace]
members = ["spanscope-macros", "spanscope", "cargo-spanscope"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
repository = "https://github.com/GNP50/spanscope"
homepage = "https://github.com/GNP50/spanscope"
keywords = ["profiling", "tracing", "performance", "flamegraph", "instrumentation"]
categories = ["development-tools::profiling", "development-tools::cargo-plugins", "visualization"]

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
schemars = "0.8.22"
syn = { version = "2.0.119", features = ["full", "parsing"] }
quote = "1.0.47"
proc-macro2 = "1.0.107"
proc-macro-crate = "3.2.0"
trybuild = "1.0.101"
criterion = "0.5.1"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docsrs)'] }
