// Collect the license of every package whose code ends up inside the bundled
// report, and write THIRD-PARTY-NOTICES.md. MIT and BSD require their notice to
// travel with every copy, and Apache-2.0 section 4(d) requires any NOTICE file
// to be reproduced, so the generated file ships next to the viewer asset.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const modules = resolve(root, 'node_modules');

// The bundled set is taken from the sourcemaps of the production build, so it
// reflects the code that actually shipped rather than the dependency tree.
// `npm run notices` builds with sourcemaps first; the resolved list is kept in
// bundled-packages.json so a reviewer can see it and CI can detect drift.
const listPath = resolve(import.meta.dirname, 'bundled-packages.json');
const maps = readdirSync(resolve(root, 'dist/assets')).filter((f) => f.endsWith('.map'));
let bundled;
if (maps.length > 0) {
  const found = new Set();
  for (const file of maps) {
    const map = JSON.parse(readFileSync(resolve(root, 'dist/assets', file), 'utf8'));
    for (const source of map.sources ?? []) {
      const match = /node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(source);
      if (match) found.add(match[1]);
    }
  }
  bundled = [...found].sort();
  writeFileSync(listPath, `${JSON.stringify(bundled, null, 2)}\n`);
} else {
  bundled = JSON.parse(readFileSync(listPath, 'utf8'));
}

const licenseFile = (dir) => {
  if (!existsSync(dir)) return null;
  const name = readdirSync(dir).find((f) => /^(LICENSE|LICENCE|COPYING)(\.|$)/i.test(f));
  return name ? readFileSync(resolve(dir, name), 'utf8').trim() : null;
};

const sections = [];
for (const name of bundled) {
  const dir = resolve(modules, name);
  const meta = JSON.parse(readFileSync(resolve(dir, 'package.json'), 'utf8'));
  const text = licenseFile(dir);
  const notice = existsSync(resolve(dir, 'NOTICE')) ? readFileSync(resolve(dir, 'NOTICE'), 'utf8').trim() : null;
  // A few packages declare a license without shipping its text; record the
  // declaration and the author so the attribution is still traceable.
  const body = text
    ? `\n\`\`\`\n${text}\n\`\`\`\n`
    : `\nThis package ships no license file. Its manifest declares ` +
      `${meta.license}${meta.author ? `, authored by ${typeof meta.author === 'string' ? meta.author : meta.author.name}` : ''}.\n`;
  sections.push(
    `## ${name} ${meta.version}\n\nSPDX-License-Identifier: ${meta.license}\n` +
      (meta.homepage ? `Homepage: ${meta.homepage}\n` : '') +
      (notice ? `\n### NOTICE\n\n\`\`\`\n${notice}\n\`\`\`\n` : '') +
      body,
  );
}

const header =
  '# Third-party notices\n\n' +
  'The offline HTML report generated by `cargo-spanscope` embeds the libraries\n' +
  'listed here. Their licenses apply to those portions of the report; spanscope\n' +
  'itself is MIT OR Apache-2.0. This file is generated by `npm run notices`.\n\n';

const out = header + sections.join('\n');
for (const path of [
  resolve(root, '../THIRD-PARTY-NOTICES.md'),
  resolve(root, '../cargo-spanscope/assets/THIRD-PARTY-NOTICES.md'),
  resolve(root, '../spanscope/assets/THIRD-PARTY-NOTICES.md'),
]) {
  writeFileSync(path, out);
}
console.log(`third-party notices: ${bundled.length} packages, ${Buffer.byteLength(out)} bytes`);
